version: '3'

services:
    product-service:
      image: php:apache
      volumes:
        - ./product:/var/www/html
      ports:
        - 5001:80

    website:
      image: php:apache
      volumes:
        - ./website:/var/www/html
      ports:
        - 5000:80
      depends_on:
        - product-service
